/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedQuestion
 */
export interface PatchedQuestion {
    /**
     * 
     * @type {number}
     * @memberof PatchedQuestion
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedQuestion
     */
    questionText?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedQuestion
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the PatchedQuestion interface.
 */
export function instanceOfPatchedQuestion(value: object): boolean {
    return true;
}

export function PatchedQuestionFromJSON(json: any): PatchedQuestion {
    return PatchedQuestionFromJSONTyped(json, false);
}

export function PatchedQuestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedQuestion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'questionText': json['question_text'] == null ? undefined : json['question_text'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function PatchedQuestionToJSON(value?: Omit<PatchedQuestion, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'question_text': value['questionText'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

