/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Question
 */
export interface Question {
    /**
     * 
     * @type {number}
     * @memberof Question
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Question
     */
    questionText: string;
    /**
     * 
     * @type {Date}
     * @memberof Question
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Question interface.
 */
export function instanceOfQuestion(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('questionText' in value)) return false;
    if (!('createdAt' in value)) return false;
    return true;
}

export function QuestionFromJSON(json: any): Question {
    return QuestionFromJSONTyped(json, false);
}

export function QuestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Question {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'questionText': json['question_text'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function QuestionToJSON(value?: Omit<Question, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'question_text': value['questionText'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

